using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace evidence
{
    public partial class hlavniForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        evidence.EvidenceLidiEntities dbContext;

        public hlavniForm()
        {
            InitializeComponent();
            // This line of code is generated by Datas Source Configuration Wizard
            // Instantiate a new DBContext            
            dbContext = new evidence.EvidenceLidiEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Lide.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.Lide.Local.ToBindingList();
        }

        private void pridatButton_Click(object sender, EventArgs e)
        {
            pridaniForm pridatForm = new pridaniForm(dbContext);      //formular pridani osoby
            if (pridatForm.ShowDialog() == DialogResult.OK)
            {
                gridControl1.DataSource = dbContext.Lide.Local.ToBindingList();
                gridView1.RefreshData();
            }
        }

        private void editovatButton_Click(object sender, EventArgs e)
        {
            Lide editClovek = new Lide();

            editClovek.id_osoba = Int32.Parse(gridView1.GetFocusedRowCellDisplayText(idColumn));
            editClovek.jmeno = gridView1.GetFocusedRowCellDisplayText(jmenoColumn);
            editClovek.prijmeni = gridView1.GetFocusedRowCellDisplayText(prijmeniColumn);
            editClovek.ulice = gridView1.GetFocusedRowCellDisplayText(uliceColumn);
            editClovek.obec = gridView1.GetFocusedRowCellDisplayText(obecColumn);
            editClovek.telefon = Int32.Parse(gridView1.GetFocusedRowCellDisplayText(telefonColumn));
            editClovek.email = gridView1.GetFocusedRowCellDisplayText(emailColumn);

            editaceForm editForm = new editaceForm(dbContext, editClovek);      //formular pridani osoby
            editForm.Show();
        }
    }
}
