//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evidence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lide
    {
        public int id_osoba { get; set; }
        public string jmeno { get; set; }
        public string prijmeni { get; set; }
        public string ulice { get; set; }
        public string obec { get; set; }
        public int telefon { get; set; }
        public string email { get; set; }
    }
}
